## One hot encoding example

In [27]:
import numpy as np
def get_one_hot(input_vector):
    result=[]
    for i in  input_vector:
        newval=np.zeros(max(input_vector))
        newval.itemset(i-1,1)
        result.append(newval)
    return result
        
        
get_one_hot([1,5,2,4,3])

[array([ 1.,  0.,  0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  0.,  1.]),
 array([ 0.,  1.,  0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  1.,  0.]),
 array([ 0.,  0.,  1.,  0.,  0.])]

## Missing data imputation

In [62]:
import numpy as np
import pandas as pd
from scipy import stats
np.seterr(invalid='ignore')
means=[]
modes=[]
medians=[]
input_data=np.array([[6,5,3,np.NAN], [6,np.NAN, 5, 3],[np.NAN, 8,2,6],[2,3,np.NAN,1]])
for i in input_data[:].T:
    means.append( np.nanmean(i))
    modes.append(stats.mode(i).mode[0])
    medians.append(np.nanmedian(i))
print means
print modes
print medians


[4.666666666666667, 5.333333333333333, 3.3333333333333335, 3.3333333333333335]
[6.0, 3.0, 2.0, 1.0]
[6.0, 5.0, 3.0, 3.0]
